# Generated by Django 3.2.5 on 2021-07-13 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caterer', '0002_auto_20210713_0551'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='caterer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='caterer.caterer'),
        ),
        migrations.AddField(
            model_name='service',
            name='days_to_deliver',
            field=models.CharField(default=5, help_text='How many days will it take it to deliver the service.', max_length=2),
            preserve_default=False,
        ),
    ]
