# Generated by Django 3.2.5 on 2021-08-10 12:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caterer', '0004_alter_service_days_to_deliver'),
    ]

    operations = [
        migrations.AddField(
            model_name='caterer',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='days_to_deliver',
            field=models.PositiveSmallIntegerField(help_text='How many days will it take it to deliver the service.', validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)]),
        ),
    ]
