# Generated by Django 3.2.5 on 2021-10-28 13:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caterer', '0005_auto_20210810_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='minimum_order_quantity',
            field=models.PositiveSmallIntegerField(default=1, help_text='What is the minimum order quantity you an accept?', validators=[django.core.validators.MaxValueValidator(7), django.core.validators.MinValueValidator(1)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='service',
            name='days_to_deliver',
            field=models.PositiveSmallIntegerField(help_text='How many days will it take it to deliver the service.', validators=[django.core.validators.MaxValueValidator(7), django.core.validators.MinValueValidator(1)]),
        ),
    ]
